const Menu  = [{
    id: 1,
    image: "images/allupakora.jpg.jpg",
    name: "allupakora",
    category: "breakfast",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 2,
    image: "images/chole.jpg.jpg",
    name: "chole",
    category: "dinner",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 3,
    image: "images/corn.jpg.jpg",
    name: "corn",
    category: "breakfast",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 4,
    image: "images/maggi.jpg.jpg",
    name: "maggi",
    category: "lunch",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 5,
    image: "images/momo.jpg.jpg",
    name: "momo",
    category: "dinner",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 6,
    image: "images/pizza.jpg.jpg",
    name: "pizza",
    category: "evening",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 7,
    image: "images/samosa.jpg.jpg",
    name: "samosa",
    category: "dinner",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 8,
    image: "images/sweet.jpg.jpg",
    name: "sweet",
    category: "evening",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},
{
    id: 9,
    image: "images/vegthali.jpg.jpg",
    name: "vegthali",
    category: "lunch",
    price: 25,
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. unknown printer took a galley of type and scrambled it to make a type specimen book",
},

];

export default Menu;